version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    reviewers:
      - wkhal
    labels:
      - dependencies
    commit-message:
      prefix: 'deps'
    groups:
      dev-dependencies:
        patterns:
          - '@types/*'
          - '@eslint/*'
          - 'eslint*'
          - 'prettier'
          - 'vitest'
          - 'typescript*'
        update-types:
          - 'minor'
          - 'patch'
